config/routes.rb
FatFreeCRM::Application.routes.draw do

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'options'    => 'home#options'
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup
  match 'timeline'   => 'home#timeline',           :as => :timeline
  match 'timezone'   => 'home#timezone',           :as => :timezone
  match 'toggle'     => 'home#toggle'

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put :attach
      post :discard
    end
  end

  resources :campaigns do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :contacts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :leads do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      get  :convert
      post :discard
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :tasks do
    collection do
      get  :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get  :search
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :settings
    resources :plugins
  end

  match '/:controller(/:action(/:id))'
end

app/helpers/tasks_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module TasksHelper

  # Sidebar checkbox control for filtering tasks by due date -- used for
  # pending and assigned views only.
  #----------------------------------------------------------------------------
  def task_filter_checbox(view, filter, count)
    name = "filter_by_task_#{view}"
    checked = (session[name] ? session[name].split(",").include?(filter.to_s) : count > 0)
    onclick = remote_function(
      :url      => { :action => :filter, :view => view },
      :with     => "'filter='+this.value+'&checked='+this.checked",
      :loading  => "$('loading').show()",
      :complete => "$('loading').hide()"
    )
    check_box_tag("filters[]", filter, checked, :onclick => onclick)
  end

  #----------------------------------------------------------------------------
  def filtered_out?(view, filter = nil)
    name = "filter_by_task_#{view}"
    if filter
      filters = (session[name].nil? ? [] : session[name].split(","))
      !filters.include?(filter.to_s)
    else
      session[name].blank?
    end
  end

  #----------------------------------------------------------------------------
  def link_to_task_edit(task, bucket)
    link_to(t(:edit), edit_task_path(task),
      :method => :get,
      :with   => "{ bucket: '#{bucket}', view: '#{@view}', previous: crm.find_form('edit_task') }",
      :remote => true
    )
  end

  #----------------------------------------------------------------------------
  def link_to_task_delete(task, bucket)
    link_to(t(:delete) + "!", task_path(task),
      :method => :delete,
      :with   => "{ bucket: '#{bucket}', view: '#{@view}' }",
      :before => visual_effect(:highlight, dom_id(task), :startcolor => "#ffe4e1"),
      :remote => true
    )
  end

  #----------------------------------------------------------------------------
  def link_to_task_complete(pending, bucket)
    onclick = %Q/$("#{dom_id(pending, :name)}").style.textDecoration="line-through";/
    onclick << remote_function(:url => complete_task_path(pending), :method => :put, :with => "'bucket=#{bucket}'")
  end

  # Helper to display XLS, CSV, RSS, and ATOM links for tasks.
  #----------------------------------------------------------------------------
  def links_to_task_export(view)
    token = @current_user.single_access_token

    exports = %w(xls csv).map do |format|
      link_to(format.upcase, "#{tasks_path}.#{format}?view=#{view}", :title => I18n.t(:"to_#{format}"))
    end
    feeds = %w(rss atom).map do |format|
      link_to(format.upcase, "#{tasks_path}.#{format}?view=#{view}&authentication_credentials=#{token}", :title => I18n.t(:"to_#{format}"))
    end

    (exports + feeds).join(' | ')
  end

  # Task summary for RSS/ATOM feed.
  #----------------------------------------------------------------------------
  def task_summary(task)
    summary = [ task.category.blank? ? t(:other) : t(task.category) ]
    if @view != "completed"
      if @view == "pending" && task.user != @current_user
        summary << t(:task_from, task.user.full_name)
      elsif @view == "assigned"
        summary << t(:task_from, task.assignee.full_name)
      end
      summary << "#{t(:related)} #{task.asset.name} (#{task.asset_type.downcase})" if task.asset_id?
      summary << if task.bucket == "due_asap"
        t(:task_due_now)
      elsif task.bucket == "due_later"
        t(:task_due_later)
      else
        l(task.due_at.localtime, :format => :mmddhhss)
      end
    else # completed
      summary << "#{t(:related)} #{task.asset.name} (#{task.asset_type.downcase})" if task.asset_id?
      summary << t(:task_completed_by,
                   :time_ago => distance_of_time_in_words(task.completed_at, Time.now),
                   :date     => l(task.completed_at.localtime, :format => :mmddhhss),
                   :user     => task.completor.full_name)
    end
    summary.join(', ')
  end

  #----------------------------------------------------------------------------
  def hide_task_and_possibly_bucket(id, bucket)
    update_page do |page|
      page[id].replace ""

      if Task.bucket_empty?(bucket, @current_user, @view)
        page["list_#{bucket}"].visual_effect :fade, :duration => 0.5
      end
    end
  end

  #----------------------------------------------------------------------------
  def replace_content(task, bucket = nil)
    partial = (task.assigned_to && task.assigned_to != @current_user.id) ? "assigned" : "pending"
    update_page do |page|
      page[dom_id(task)].replace_html :partial => "tasks/#{partial}", :collection => [ task ], :locals => { :bucket => bucket }
    end
  end

  #----------------------------------------------------------------------------
  def insert_content(task, bucket, view)
    update_page do |page|
      page["list_#{bucket}"].show
      page.insert_html :top, bucket, :partial => view, :collection => [ task ], :locals => { :bucket => bucket }
      page[dom_id(task)].visual_effect :highlight, :duration => 1.5
    end
  end

  #----------------------------------------------------------------------------
  def tasks_flash(message)
    update_page do |page|
      page[:flash].replace_html message
      page.call "crm.flash", :notice, true
    end
  end

  #----------------------------------------------------------------------------
  def reassign(id)
    update_page do |page|
      if @view == "pending" && @task.assigned_to != @current_user.id
        page << hide_task_and_possibly_bucket(id, @task_before_update.bucket)
        page << tasks_flash("#{t(:task_assigned, @task.assignee.full_name)} (" << link_to(t(:view_assigned_tasks), url_for(:controller => :tasks, :view => :assigned)) << ").")
      elsif @view == "assigned" && @task.assigned_to.blank?
        page << hide_task_and_possibly_bucket(id, @task_before_update.bucket)
        page << tasks_flash("#{t(:task_pending)} (" << link_to(t(:view_pending_tasks), tasks_url) << ").")
      else
        page << replace_content(@task, @task.bucket)
      end
      page << refresh_sidebar(:index, :filters)
    end
  end

  #----------------------------------------------------------------------------
  def reschedule(id)
    update_page do |page|
      page << hide_task_and_possibly_bucket(id, @task_before_update.bucket)
      page << insert_content(@task, @task.bucket, @view)
      page << refresh_sidebar(:index, :filters)
    end
  end

end

app/views/tasks/_assigned.html.haml
%li[assigned]{ highlightable(dom_id(assigned, :tools)) }
  - unless assigned.category.blank?
    .strip{:class => assigned.category}= t(assigned.category)
  - else
    .strip.white #{t :other}

  .tools{ invisible, :id => dom_id(assigned, :tools) }
    = link_to_task_edit(assigned, bucket) + " | "
    = link_to_discard(assigned) + " | " if shown_on_landing_page?
    = link_to_task_delete(assigned, bucket)

  .indent
    = link_to(assigned.assignee.full_name, user_path(assigned.assignee)) + ": "
    = auto_link h(assigned.name)
    - if assigned.asset_id?
      == #{t :related} #{link_to(h(assigned.asset.name), polymorphic_url(assigned.asset))}
    &ndash;
    %tt
      - if assigned.bucket == "due_asap"
        %span.urgent= t(:task_due_now)

      - elsif assigned.bucket == "due_later"
        = t(:task_due_later)

      - else
        - if assigned.at_specific_time?
          - if assigned.due_at < Time.now
            %span.warn= distance_of_time_in_words(assigned.due_at, Time.now)
            = t(:task_overdue) 
            = l(assigned.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:task_due_in, distance_of_time_in_words(Time.now, assigned.due_at))
            = '(' << l(assigned.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if assigned.due_at < Date.today
            %span.warn= distance_of_time_in_words(assigned.due_at, Time.now) 
            = t(:task_overdue) 
            = assigned.due_at.localtime.strftime('%b %e')
          - elsif assigned.due_at > Date.today
            = t(:task_due_in, distance_of_time_in_words(Time.now, assigned.due_at.localtime.end_of_day))
          - else
            %span.cool= t(:task_due_today)

    - unless assigned.background_info.blank?
      %div
        %dt= h(assigned.background_info)

app/views/tasks/_completed.html.haml
%li[completed]{ highlightable(dom_id(completed, :tools)) }
  - unless completed.category.blank?
    .strip{:class => completed.category}= t(completed.category)
  - else
    .strip.white #{t :other}

  .tools{ invisible, :id => dom_id(completed, :tools) }
    - if shown_on_landing_page?
      = link_to_discard(completed) + (@current_user == completed.user ? ' | ' : '')
    = link_to_task_delete(completed, bucket) if @current_user == completed.user

  .indent
    %strike= auto_link h(completed.name)
    - if completed.asset_id?
      == #{t :related} #{link_to(h(completed.asset.name), polymorphic_url(completed.asset))}
    &ndash;
    %tt
      %span.cool
        -# :task_completed_by: "completed {{time_ago}} ago by {{user}}"
        = t(:task_completed_by, :time_ago => distance_of_time_in_words(completed.completed_at, Time.now), :date => completed.completed_at, :user => ((completed.completor.id != @current_user.id) ? link_to(completed.completor.full_name, user_path(completed.completor)) : t(:me)))
    - unless completed.background_info.blank?
      %div
        %dt= h(completed.background_info)

app/views/tasks/_create.html.haml
= form_for(@task, :html => one_submit_only(:task), :remote => true) do |f|
  = link_to_close new_task_path + "?view=#{@view}"
  = hidden_field_tag :view, @view
  = hidden_field_tag "task[user_id]", @current_user.id
  = hidden_field_tag "task[asset_id]", "#{@asset.id if @asset}"
  = hidden_field_tag "task[asset_type]", "#{@asset.class if @asset}"
  = render "tasks/top_section", :f => f
  .buttonbar
    = f.submit t :create_task
    #{t :or}
    = link_to_cancel new_task_path + "?view=#{@view}"

app/views/tasks/_edit.html.haml
.remote
  = form_for(@task, :html => one_submit_only(:task), :remote => true) do |f|
    = link_to_close edit_task_path(@task)
    = hidden_field_tag :view, @view
    = hidden_field_tag "task[asset_id]", "#{@asset.id if @asset}"
    = hidden_field_tag "task[asset_type]", "#{@asset.class if @asset}"
    = render "tasks/top_section", :f => f
    .buttonbar
      = f.submit t :save_task
      == #{t :or}
      = link_to_cancel edit_task_path(@task)
      == #{t :or} #{t :move_to}
      - [ "ASAP", "Today", "Tomorrow", "This week", "Next week", "Later" ].each do |day|
        - due_day = "due_#{day.snakecase}"
        = link_to(t(due_day.to_sym), "#", :onclick => %Q/crm.reschedule_task(#{@task.id}, "#{due_day}")/)
        = " | " if day != "Later"

app/views/tasks/_empty.html.haml
#empty
  == #{t(:no_tasks, t('no_tasks_' + @view))}.
  - if @view != "completed"
    == #{t :feel_free} #{link_to(t(:create_task_small), new_task_path + "?view=#{@view}", :remote => true)}.

app/views/tasks/_pending.html.haml
%li[pending]{ highlightable(dom_id(pending, :tools)) }
  - unless pending.category.blank?
    .strip{:class => pending.category}= t(pending.category)
  - else
    .strip.white #{t :other}

  .tools{ invisible, :id => dom_id(pending, :tools) }
    = link_to_task_edit(pending, bucket) + " | "
    = link_to_discard(pending) + " | " if shown_on_landing_page?
    = link_to_task_delete(pending, bucket)

  = check_box_tag dom_id(pending, :complete), 1, false, :onclick => link_to_task_complete(pending, bucket)

  .indentwide
    %label{ :id => dom_id(pending, :name) }
      - if pending.user.id != @current_user.id
        = t(:task_from, link_to(pending.user.full_name, user_path(pending.user))).html_safe << ':'
      = auto_link h(pending.name)
      - if pending.asset_id?
        == #{t :related} #{link_to(h(pending.asset.name), polymorphic_url(pending.asset))}
      &ndash;
    %tt
      - if pending.bucket == "due_asap"
        %span.urgent= t(:task_due_now)

      - elsif pending.bucket == "due_later"
        = t(:task_due_later)

      - else
        - if pending.at_specific_time?
          - if pending.due_at < Time.now
            %span.warn= distance_of_time_in_words(pending.due_at, Time.now)
            = t(:task_overdue)
            = l(pending.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:task_due_in, distance_of_time_in_words(Time.now, pending.due_at))
            = '(' << l(pending.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if pending.due_at < Date.today
            %span.warn= distance_of_time_in_words(pending.due_at, Time.now)
            = t(:task_overdue)
            = pending.due_at.localtime.strftime('%b %e')
          - elsif pending.due_at > Date.today
            = t(:task_due_in, distance_of_time_in_words(Time.now, pending.due_at.localtime.end_of_day))
          - else
            %span.cool= t(:task_due_today)

    - unless pending.background_info.blank?
      %div
        %dt= h(pending.background_info)

app/views/tasks/_related.html.haml
%li[related]{ highlightable(dom_id(related, :tools)) }
  - unless related.category.blank?
    .strip{:class => related.category}= t(related.category)
  - else
    .strip{:style => "color:white"} #{t :other}
  %div
    .tools{ invisible, :id => dom_id(related, :tools) }
    - if related.assigned_to
      = link_to(related.assignee.full_name, user_path(related.assignee))
    - else
      = link_to(related.user.full_name, user_path(related.user))
    = ": " + related.name
    - if related.asset_id?
      == (#{t :related} #{link_to(related.asset.name, polymorphic_url(related.asset))})
    &ndash;
    %tt
      - if related.completed_at
        %span.cool
          = t(:task_completed_ago, distance_of_time_in_words(related.completed_at, Time.now))
      - elsif related.bucket == "due_asap"
        %span.urgent 
        == #{t :due_now}.
      - elsif related.bucket == "due_later"
        == #{t :due_later}.
      - elsif related.due_at < Date.today
        %span.warn= distance_of_time_in_words(related.due_at, Date.today) 
        == #{t :overdue} #{related.due_at.strftime('%b %e')}
      - elsif related.due_at > Date.today
        = t(:task_due_in, distance_of_time_in_words(Time.now, related.due_at.end_of_day))
      - else
        %span.cool
        == #{t :due_today}.
      

app/views/tasks/_selector.html.haml
%table{ :cellpadding => 3, :cellspacing => 0, :style => "width: 100%; margin: 2px 0px 10px 0px" }
  %tr
    %td{ :class => "selector left " + (@view == "pending" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{tasks_path}') }
      #{t :pending_tab}
    %td{ :class => "selector " + (@view == "assigned" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{url_for(:action => :index, :view => "assigned")}') }
      #{t :assigned_tab}
    %td{ :class => "selector right " + (@view == "completed" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{url_for(:action => :index, :view => "completed")}') }
      #{t :completed_tab}

app/views/tasks/_sidebar_index.html.haml
.filters#filters
  = render "selector"
  - if @view == "pending" || @view == "assigned"
    - Setting.unroll(:task_bucket).each do |value, key|
      .check_box{:style => "border-bottom: 1px silver dotted;"}
        %div{:style => "float:right;"}
          = @task_total[key]
        = task_filter_checbox(@view, key, @task_total[key]) << " " << t(value)
  - else # @view == "completed"
    - Setting.unroll(:task_completed).each do |value, key|
      .check_box{:style => "border-bottom: 1px silver dotted;"}
        %div{:style => "float:right;"}
          = @task_total[key]
        = task_filter_checbox(@view, key, @task_total[key]) << " " << t(value)
  .check_box
    %div{:style => "float:right;"}
      %b= @task_total[:all]
    %b== #{t(:total_tasks, t(@view + '_tasks'))}

app/views/tasks/_title.html.haml
.title_tools
  = link_to_inline(:create_task, url_for(:action => :new, :view => @view), :text => t(:create_task))
.title#title
  = (@view == "assigned" ? t(:assigned_tasks) : t(:tasks))
  = image_tag("loading.gif", :size => "16x16", :id => "loading", :style => "display: none;")

.remote#options{ hidden }
.remote#create_task{ hidden }

app/views/tasks/_top_section.html.haml
.section
  %table
    %tr
      %td(colspan="5")
        .label.top.req #{t :name}:
        = f.text_field :name, :style => "width:500px"
    %tr
      %td
        .label.req #{t :due}:
        - bucket = (params[:bucket].blank? ? @task.bucket : params[:bucket]) || "due_asap"
        - if @task.bucket != "specific_time"
          = f.select :bucket, @bucket, { :selected => bucket.to_sym }, { :style => "width:160px;", :onchange => "crm.flip_calendar(this.value)" }
          = f.text_field :calendar, :style => "width:160px; display:none;", :autocomplete => :off
        - else
          = f.select :bucket, @bucket, { :selected => :specific_time }, { :style => "width:160px; display:none;", :onchange => "crm.flip_calendar(this.value)" }
          = f.text_field :calendar, :value => (Setting.task_calendar_with_time ? l(f.object.due_at.localtime, :format => :mmddyyyy_hhmm) : l(f.object.due_at.to_date, :format => :mmddyyyy)), :style => "width:160px;", :autocomplete => :off
      %td= spacer
      %td
        .label.req #{t :assign_to}:
        = collection_select :task, :assigned_to, @users, :id, :full_name, { :include_blank => t(:myself) }, { :style => "width:160px", :disabled => @task.assigned_to == @current_user.id }
      %td= spacer
      %td
        .label.req #{t :category}:
        = f.select :category, @category, { :selected => @task.category.blank? ? nil : @task.category.to_sym, :include_blank => t(:select_blank) }, { :style => "width:160px" }

    - if Setting.background_info && Setting.background_info.include?(:task)
      %tr
        %td(colspan="5")
          .label= t(:extra_info).capitalize << ':'
          = f.text_area :background_info, :style =>"width:500px", :rows => 3

    = hook(:task_top_section_bottom, self, :f => f)

app/views/tasks/index.html.haml
= styles_for :task

- if @view == "completed"
  - buckets = Setting.unroll(:task_completed)
  .title
    = t(:completed_tasks)
    = image_tag("loading.gif", :size => "16x16", :id => "loading", :style => "display: none;")
- else
  - buckets = Setting.unroll(:task_bucket)
  = render "title"

.log#tasks
  - buckets.each do |value, key|
    %div{ hidden_if(filtered_out?(@view, key)), :id => "list_#{key}" }
      %h3{:class => key}= t(value)
      .bucket{:id => key}= render :partial => @view, :collection => @tasks[key] || [], :locals => { :bucket => key }
  - if @tasks.values.flatten.blank?
    = render "empty"

#export= raw links_to_task_export(@view)