config/routes.rb
FatFreeCRM::Application.routes.draw do

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'options'    => 'home#options'
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup
  match 'timeline'   => 'home#timeline',           :as => :timeline
  match 'timezone'   => 'home#timezone',           :as => :timezone
  match 'toggle'     => 'home#toggle'

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put :attach
      post :discard
    end
  end

  resources :campaigns do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :contacts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :leads do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      get  :convert
      post :discard
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :tasks do
    collection do
      get  :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get  :search
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :settings
    resources :plugins
  end

  match '/:controller(/:action(/:id))'
end

app/controllers/admin/users_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class Admin::UsersController < Admin::ApplicationController
  before_filter "set_current_tab('admin/users')", :only => [ :index, :show ]

  # GET /admin/users
  # GET /admin/users.xml                                                   HTML
  #----------------------------------------------------------------------------
  def index
    @users = get_users(:page => params[:page])

    respond_to do |format|
      format.html # index.html.haml
      format.js   # index.js.rjs
      format.xml  { render :xml => @users }
      format.xls  { send_data @users.to_xls, :type => :xls }
      format.csv  { send_data @users.to_csv, :type => :csv }
      format.rss  { render "common/index.rss.builder" }
      format.atom { render "common/index.atom.builder" }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  #----------------------------------------------------------------------------
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.xml  { render :xml => @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml                                               AJAX
  #----------------------------------------------------------------------------
  def new
    @user = User.new

    respond_to do |format|
      format.js   # new.js.rjs
      format.xml  { render :xml => @user }
    end
  end

  # GET /admin/users/1/edit                                                AJAX
  #----------------------------------------------------------------------------
  def edit
    @user = User.find(params[:id])

    if params[:previous].to_s =~ /(\d+)\z/
      @previous = User.find($1)
    end

  rescue ActiveRecord::RecordNotFound
    @previous ||= $1.to_i
    respond_to_not_found(:js) unless @user
  end

  # POST /admin/users
  # POST /admin/users.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def create
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    @user = User.new(params[:user])
    @user.admin = (params[:user][:admin] == "1")

    respond_to do |format|
      if @user.save_without_session_maintenance
        @users = get_users
        format.js   # create.js.rjs
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.js   # create.js.rjs
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml                                                 AJAX
  #----------------------------------------------------------------------------
  def update
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    @user = User.find(params[:id])
    @user.admin = (params[:user][:admin] == "1")

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.js   # update.js.rjs
        format.xml  { head :ok }
      else
        format.js   # update.js.rjs
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end

  # GET /admin/users/1/confirm                                             AJAX
  #----------------------------------------------------------------------------
  def confirm
    @user = User.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml                                              AJAX
  #----------------------------------------------------------------------------
  def destroy
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.destroy
        format.js   # destroy.js.rjs
        format.xml  { head :ok }
      else
        flash[:warning] = t(:msg_cant_delete_user, @user.full_name)
        format.js   # destroy.js.rjs
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /users/search/query                                                AJAX
  #----------------------------------------------------------------------------
  def search
    @users = get_users(:query => params[:query], :page => 1)

    respond_to do |format|
      format.js   { render :index }
      format.xml  { render :xml => @users.to_xml }
    end
  end

  # POST /users/auto_complete/query                                        AJAX
  #----------------------------------------------------------------------------
  # Handled by Admin::ApplicationController :auto_complete

  # PUT /admin/users/1/suspend
  # PUT /admin/users/1/suspend.xml                                         AJAX
  #----------------------------------------------------------------------------
  def suspend
    @user = User.find(params[:id])
    @user.update_attribute(:suspended_at, Time.now) if @user != @current_user

    respond_to do |format|
      format.js   # suspend.js.rjs
      format.xml  { render :xml => @user }
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end

  # PUT /admin/users/1/reactivate
  # PUT /admin/users/1/reactivate.xml                                      AJAX
  #----------------------------------------------------------------------------
  def reactivate
    @user = User.find(params[:id])
    @user.update_attribute(:suspended_at, nil)

    respond_to do |format|
      format.js   # reactivate.js.rjs
      format.xml  { render :xml => @user }
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end


  private
  #----------------------------------------------------------------------------
  def get_users(options = {})
    self.current_page  = options[:page]  if options[:page]
    self.current_query = options[:query] if options[:query]

    wants = request.format
    scope = User.by_id
    scope = scope.search(current_query)           unless current_query.blank?
    scope = scope.unscoped                        if wants.csv?
    scope = scope.paginate(:page => current_page) if wants.html? || wants.js? || wants.xml?
    scope
  end
end

app/helpers/admin/users_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module Admin::UsersHelper

  def link_to_suspend(user)
    link_to(t(:suspend) + "!", suspend_admin_user_path(user), :method => :put, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_reactivate(user)
    name = user.awaits_approval? ? t(:approve) + "!" : t(:reactivate) + "!"
    link_to(name, reactivate_admin_user_path(user), :method => :put, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_confirm(user)
    link_to(t(:delete) + "?", confirm_admin_user_path(user), :method => :get, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_delete(user)
    link_to_remote(t(:yes_button),
      :method => :delete,
      :url => admin_user_path(user),
      :before => visual_effect(:highlight, dom_id(user), :startcolor => "#ffe4e1")
    )
  end

  # User summary info for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def user_summary(user)
    summary = []
    title_and_company = user.title.blank? ? '' : h(user.title)
    title_and_company << " #{t(:at)} #{user.company}" unless user.company.blank?
    summary << title_and_company unless title_and_company.blank?
    summary << t('pluralize.login', user.login_count) if user.last_request_at && user.login_count > 0
    summary << user.email
    summary << "#{t :phone_small}: #{user.phone}" unless user.phone.blank?
    summary << "#{t :mobile_small}: #{user.mobile}" unless user.mobile.blank?
    summary << if !user.suspended?
      t(:user_since, l(user.created_at.to_date, :format => :mmddyy))
    elsif user.awaits_approval?
      t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))
    else
      t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))
    end
    summary << if user.awaits_approval?
      t(:user_signed_up)
    elsif user.suspended?
      t(:user_suspended)
    elsif user.admin?
      t(:user_admin)
    else
      t(:user_active)
    end
    summary.join(', ')
  end
end

app/helpers/users_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module UsersHelper
  
  def language_for(user)
    if user.preference[:locale]
      locale, language = languages.detect{ |locale, language| locale == user.preference[:locale] }
    end
    language || "English"
  end

  def sort_by_language
    languages.sort.map do |locale, language|
      %Q[{ name: "#{language}", on_select: function() { #{redraw(:locale, [ locale, language ], url_for(:action => :redraw))} } }]
    end
  end
end

app/views/admin/users/_confirm.html.haml
.confirm[@user, :confirm]
  #{t :user_confirm_delete}
  #{t :delete} <b>#{@user.full_name}</b>?
  = link_to(t(:yes_button), admin_user_path(@user), :method => :delete) << " : "
  = link_to_function(t(:no_button), "crm.flick('#{dom_id(@user, :confirm)}', 'remove')")

app/views/admin/users/_create.html.haml
= form_for([:admin, @user], :html => one_submit_only(:user).merge({:autocomplete => 'off'}), :remote => true) do |f|
  = link_to_close new_admin_user_path

  = f.error_messages :object_name => t('user')

  = render "admin/users/profile", :f => f
  .buttonbar
    = f.submit t(:create_user)
    #{t :or}
    = link_to_cancel new_admin_user_path

app/views/admin/users/_edit.html.haml
.remote
  = form_for([:admin, @user], :html => one_submit_only(:user).merge({:autocomplete => 'off'}), :remote => true) do |f|
    = link_to_close edit_admin_user_path(@user)

    = f.error_messages :object_name => t('user')

    = render "admin/users/profile", :f => f, :edit => true
    .buttonbar
      = f.submit t(:save_user)
      #{t :or}
      = link_to_cancel edit_admin_user_path(@user)

app/views/admin/users/_profile.html.haml
- edit ||= false
.section
  %table
    %tr
      %td
        .label.top.req #{t :username}:
        = f.text_field :username
      %td= spacer
      %td
        .label.top.req #{t :email}:
        = f.text_field :email
    %tr
      %td
        .label #{t :password}:
        = f.password_field :password
      %td= spacer
      %td
        .label #{t :password_confirmation}:
        = f.password_field :password_confirmation
    %tr
      %td(colspan=3)
        .check_box(style="margin-top:6px")
          -# Sorry, you can't revoke Admin rights from yourself.
          = f.check_box(:admin, { :disabled => edit && @user == @current_user }) << " " << t(:user_is_admin)
.subtitle #{t :personal_information}
.section
  %table
    %tr
      %td
        .label #{t :first_name}:
        = f.text_field :first_name
      %td= spacer
      %td
        .label #{t :last_name}:
        = f.text_field :last_name
    %tr
      %td
        .label #{t :job_title}:
        = f.text_field :title
      %td= spacer
      %td
        .label #{t :company}:
        = f.text_field :company

app/views/admin/users/_sidebar_index.html.haml
.filters#filters
  = render "common/search"

app/views/admin/users/_user.html.haml
%li[user]{ highlightable(dom_id(user, :tools)) }

  - if user.awaits_approval?
    .strip.signed_up #{t :user_signed_up}
  - elsif user.suspended?
    .strip.suspended #{t :user_suspended}
  - elsif user.admin?
    .strip.admin #{t :user_admin}
  - else
    .strip.active #{t :user_active}

  = gravatar_for(user, :size => "30x30")

  .indentfull
    .tools{ invisible, :id => dom_id(user, :tools) }
      = link_to_edit(user, :url => edit_admin_user_path(user)) << " | "

      - if user.suspended?
        = link_to_reactivate(user) << " | "
      - elsif user != @current_user
        = link_to_suspend(user) << " | "
      - else
        = "<font color='silver'>#{t :suspend}!</font> | ".html_safe

      - if user != @current_user
        = link_to_confirm(user)
      - else
        %span.grayed #{t :delete}?

    %span.black #{link_to(h(user.full_name), user)} (#{user.username})
    %tt
      = "- #{h(user.title)}" unless user.title.blank?
      = " " + t(:at) + " " + h(user.company) unless user.company.blank?

      %span.black= "|"
      - if user.last_request_at && user.login_count > 0
        = t('pluralize.login', user.login_count)
        %span.black= "|"

      - if user.awaits_approval?
        %b.cool #{t :user_awaits_approval}
      - elsif user.last_request_at
        %span.cool #{t(:last_seen, time_ago_in_words(user.last_request_at))}
      - else
        %span.warn #{t :user_never_logged_in}
    %dt{ :style => "padding: 2px 0px 0px 0px" }
      = link_to_email(user.email.to_s) << " | "
      = "#{t :phone_small}: <b>".html_safe + user.phone << "</b> | ".html_safe if user.phone?
      = "#{t :mobile_small}: <b>".html_safe + user.mobile << "</b> | ".html_safe if user.mobile?

      - if !user.suspended?
        %span #{t(:user_since, l(user.created_at.to_date, :format => :mmddyy))}
      - elsif user.awaits_approval?
        %b.cool #{t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))}
      - else
        %span.warn #{t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))}

app/views/admin/users/index.html.haml
= styles_for :user

.title_tools
  = link_to_inline(:create_user, new_admin_user_path, :text => t(:create_user))

.title
  %span#create_user_title #{t :users}
  = image_tag("loading.gif", :size => "16x16", :id => "loading", :style => "display: none;")
.remote#create_user{ hidden }

.list#users= render @users
#paginate= render "common/paginate"
#export= render "common/export"

app/views/admin/users/show.html.haml
.title= h(@user.full_name)
%p
:erb
  <%= link_to t(:edit), edit_admin_user_path(@user) %> |
  <%= link_to t(:back), admin_users_path %>